// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// dshotx4 //
// ------- //

#define dshotx4_wrap_target 0
#define dshotx4_wrap 3

static const uint16_t dshotx4_program_instructions[] = {
	//     .wrap_target
	0x80e0, //  0: pull   ifempty block
	0xed0f, //  1: set    pins, 15               [13]
	0x6d04, //  2: out    pins, 4                [13]
	0xea00, //  3: set    pins, 0                [10]
	//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshotx4_program = {
	.instructions = dshotx4_program_instructions,
	.length = 4,
	.origin = -1,
};

static inline pio_sm_config dshotx4_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + dshotx4_wrap_target, offset + dshotx4_wrap);
	return c;
}
#endif
