[env:seeed_xiao_rp2350]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2350
board_build.f_cpu = 240000000L
framework = arduino
build_src_filter = +<*> -<**/tests/>
board_build.filesystem_size = 256k
build_flags = -Wno-deprecated-declarations -Ilib/flatbuffers-master/flatbuffers-master/include

[env:dshot_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<tests/dshot_test.cpp> -<main.cpp> -<gnc/>

[env:imu_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<tests/imu_test.cpp> -<main.cpp> -<gnc/>
monitor_speed = 115200

[env:elrs_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<*> -<main.cpp> -<gnc/> -<tests/> +<tests/elrs_test.cpp>
monitor_speed = 115200