[env:seeed_xiao_rp2350]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2350
framework = arduino

[env:dshot_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<hal/tests/dshot.cpp> -<main.cpp> -<gnc/>