[env:seeed_xiao_rp2350]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2350
framework = arduino
build_src_filter = +<*> -<**/tests/>

[env:dshot_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<tests/dshot_test.cpp> -<main.cpp> -<gnc/>

[env:imu_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<tests/imu_test.cpp> -<main.cpp> -<gnc/>
monitor_speed = 115200

[env:elrs_test]
extends = env:seeed_xiao_rp2350
build_src_filter = +<tests/elrs_test.cpp> -<main.cpp> -<gnc/>
monitor_speed = 115200