import os
import re

def verify_generated_offsets():
    # Hardcoded expected offsets from original payloadLength === 304 branch in app.js
    expected = {
        "vbat": 48,
        "rcArm": 24,
        "rcMod": 28,
        "rcThr": 32,
        "rcRol": 36,
        "rcPit": 40,
        "rcYaw": 44,
        "armed": 80,
        "mode": 84,
        "m1": 88,
        "m2": 92,
        "m3": 96,
        "m4": 100,
        "s1": 104,
        "s2": 108,
        "s3": 112,
        "s4": 116,
        "gx": 128,
        "gy": 132,
        "gz": 136,
        "ax": 12,
        "ay": 16,
        "az": 20,
        "halTime": 52,
        "timeImu": 56,
        "timeRcrx": 60,
        "timeMotors": 64,
        "timeServos": 68,
        "gncTime": 224,
        "timeNav": 228,
        "timeCtl": 232,
        "timeAlloc": 236,
        "cgx": 212,
        "cgy": 216,
        "cgz": 220,
        "effRol": 192,
        "effPit": 196,
        "effYaw": 200,
        "isCalibrating": 244,
        "progress": 248
    }

    # Load generated telemetry_layout.js
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    layout_path = os.path.join(project_root, "configurator", "telemetry_layout.js")
    
    if not os.path.exists(layout_path):
        print(f"ERROR: telemetry_layout.js not found at {layout_path}")
        return False

    with open(layout_path, "r") as f:
        content = f.read()

    # Extract ALLb_LAYOUT object contents
    match = re.search(r"const ALLb_LAYOUT = \{(.*?)\};", content, re.DOTALL)
    if not match:
        print("ERROR: Failed to parse ALLb_LAYOUT from telemetry_layout.js")
        return False

    layout_body = match.group(1)
    generated = {}
    for line in layout_body.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        parts = line.split(":")
        if len(parts) == 2:
            key = parts[0].strip()
            val = int(parts[1].replace(",", "").strip())
            generated[key] = val

    # Verify size
    size_match = re.search(r"const ALLb_SIZE = (\d+);", content)
    if not size_match:
        print("ERROR: Failed to parse ALLb_SIZE from telemetry_layout.js")
        return False
    generated_size = int(size_match.group(1))

    if generated_size != 304:
        print(f"ERROR: Generated size {generated_size} does not match expected size 304")
        return False

    # Compare layouts
    errors = 0
    for key, expected_offset in expected.items():
        if key not in generated:
            print(f"ERROR: Generated layout is missing key '{key}'")
            errors += 1
            continue
        gen_offset = generated[key]
        if gen_offset != expected_offset:
            print(f"ERROR: Offset mismatch for key '{key}': expected {expected_offset}, got {gen_offset}")
            errors += 1

    if errors == 0:
        print("SUCCESS: Offset verification passed perfectly! All autogenerated offsets match the original 304-byte branch exactly.")
        return True
    else:
        print(f"FAILURE: Offset verification failed with {errors} errors.")
        return False

if __name__ == "__main__":
    verify_generated_offsets()
